version: '3.1'
services:

  dps-welcome:
    image: mojdigitalstudio/dps-welcome:latest
    container_name: dps-welcome
    ports:
    - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    environment:
    - SERVER_PORT=8080
