---
kind: Service
apiVersion: v1
metadata:
  name: s3-assets
spec:
  type: ExternalName
  externalName: {{ .Values.s3_bucket_assets }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
